name: tefzon
version: 1.0.0+1
publish_to: none
description: Tefzon mobile app
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  device_preview: 1.1.0
  google_fonts: 3.0.1
  shared_preferences: 2.0.15
  google_sign_in: 5.3.3
  device_info_plus: 4.0.0
  firebase_auth: 3.4.1
  get_storage: 2.0.3
  http: 0.13.4
  iconify_flutter: 0.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/images/
    - asset/favourite.json
  uses-material-design: true

